import MaterialCommunityIcons from '@expo/vector-icons/MaterialCommunityIcons';
import { ComponentProps } from 'react';
import { OpaqueColorValue, type StyleProp, type TextStyle } from 'react-native';

type IconMapping = Record<string, string>;

const MAPPING: IconMapping = {
  'house.fill': 'home',
  'feather.fill': 'email', 
  'evilcons.fill': 'lock',
  'eye': 'eye',
  'eye-off': 'eye-off',
  'google.fill': 'google',  
  'ionicons.fill': 'chevron-left',
  'entypo.fill': 'shield-lock',
  'attach-email': 'email-check-outline',
  'clock.fill': 'clock',
  'gearshaper.fill': 'cog',
  'person.fill': 'account',
  'magnifyingglass': 'magnify',
  'bluetooth': 'bluetooth',
  'location-sharp': 'map-marker',
  'add': 'plus',            
  'remove': 'minus',         
  'locate': 'crosshairs-gps', 
  'message-text': 'message-text', 
  'heart.fill': 'heart',
  'heart.outline': 'heart-outline',
  'clock.outline': 'clock-outline',
  'chevron.right': 'chevron-right',
  'chevron.left': 'chevron-left',
  'chevron.up': 'chevron-up',
  'chevron.down': 'chevron-down',
  'star': 'star',
  'bell': 'bell',
  'moon': 'weather-night', 
  'watch': 'watch', 
  'lightning': 'lightning-bolt',
  'logout': 'logout',
  'bookmark': 'bookmark',
  'content-save': 'content-save',
  'check': 'check',
  'checkmark': 'check',
  'check-circle': 'check-circle',
  'vibrate': 'vibrate',  
  'trash.fill': 'delete',   
  'plus': 'plus',
  'star.fill':   'star-outline',
  'alert-outline': 'alert-outline',
  'satellite-variant': 'satellite-variant',
  'chart-bar': 'chart-bar',
  'shield-alert': 'shield-alert',
  'sparkles': 'auto-fix',
  'map': 'map',
  'photo.fill': 'image',
  'car.fill': 'car',
  'barcode': 'barcode',
  'checkmark.circle.fill': 'check-circle',
  'pencil': 'pencil',
  'trash': 'delete',
  'person.crop.circle.badge.plus': 'account-plus',
  'xmark': 'close',
  'applewatch': 'watch',
  'location.fill': 'map-marker',
  'link.badge.plus': 'link-plus',
  'circle': 'circle-outline',
  'square': 'checkbox-blank-outline',
  'checkmark.square.fill': 'checkbox-marked',
  'bluetooth-off': 'bluetooth-off',
  'person.3.fill': 'account-group',
  'cloud-alert': 'cloud-alert',
  'cloud-off-outline': 'cloud-off-outline',
  'alert-circle-outline': 'alert-circle-outline',
  'account-alert': 'account-alert',
  'car.2.fill': 'car-info',
  'people-sharp': 'account-group',
  'shield-check': 'shield-check',
  'lock-open-variant': 'lock-open-variant',
  'weather-sunny': 'weather-sunny',
  'run': 'run',
  'content-cut': 'content-cut',
  'hand-back-right': 'hand-back-right',
  'alert-circle': 'alert-circle',
  'heart': 'heart',
  'water': 'water',
  'information-circle': 'information',
  'cpu': 'memory',
  'move.3d': 'axis-arrow',
  'heart.text.square': 'heart-pulse',
  'bolt.fill': 'lightning-bolt',
  'info.circle': 'information-outline',
  'gas-station': 'gas-station',
  'human-male-female': 'human-male-female',
  'boom-gate-outline': 'boom-gate-outline',
  'traffic-light': 'traffic-light',
  'car-sport': 'car-sports',
  'pause-circle': 'pause-circle',
  'shield-off': 'shield-off',
  'shield-off-outline': 'shield-off-outline'
};

export function IconSymbol({ name, size = 24, color, style }: { name: keyof typeof MAPPING | string; size?: number; color: string | OpaqueColorValue; style?: StyleProp<TextStyle>; }) {
  const mapped = MAPPING[name] ?? 'help-circle';
  return <MaterialCommunityIcons color={color as string} size={size} name={mapped as ComponentProps<typeof MaterialCommunityIcons>['name']} style={style} />;
}